// <auto-generated>
using SQLite;
using NorWnd.Xam.ModelData;

namespace NorWnd.Xam.ModelData.NW
{
	[Table("Categories")]
	public partial class Category
	{

		[PrimaryKey]
		public int CategoryID { get; set; }

		public string CategoryName { get; set; }
		public string? Description { get; set; }
	}
}
