// <auto-generated>
using SQLite;
using NorWnd.Xam.ModelData;

namespace NorWnd.Xam.ModelData.NW
{
	[Table("CustomerDemographics")]
	public partial class CustomerDemographic
	{
		public string? CustomerDesc { get; set; }

		[PrimaryKey]
		public string CustomerTypeID { get; set; }

	}
}
