// <auto-generated>
using SQLite;
using NorWnd.Xam.ModelData;

namespace NorWnd.Xam.ModelData.NW
{
	[Table("Customers")]
	public partial class Customer
	{
		public string Address { get; set; }
		public string City { get; set; }
		public string CompanyName { get; set; }
		public string ContactName { get; set; }
		public string ContactTitle { get; set; }
		public string Country { get; set; }

		[PrimaryKey]
		public string CustomerID { get; set; }

		public string Fax { get; set; }
		public string Phone { get; set; }
		public string PostalCode { get; set; }
		public string Region { get; set; }
	}
}
