// <auto-generated>
using SQLite;
using NorWnd.Xam.ModelData;

namespace NorWnd.Xam.ModelData.NW
{
	[Table("CustomerCustomerDemo")]
	public partial class CustomerCustomerDemo
	{

		[Indexed(Name = "CustomerCustomerDemo", Order = 1, Unique = true)]
		public string CustomerID { get; set; }


		[Indexed(Name = "CustomerCustomerDemo", Order = 2, Unique = true)]
		public string CustomerTypeID { get; set; }

	}
}
