// <auto-generated>
using SQLite;
using NorWnd.Xam.ModelData;

namespace NorWnd.Xam.ModelData.NW
{
	[Table("EmployeeTerritories")]
	public partial class EmployeeTerritory
	{

		[Indexed(Name = "EmployeeTerritory", Order = 1, Unique = true)]
		public int EmployeeID { get; set; }


		[Indexed(Name = "EmployeeTerritory", Order = 2, Unique = true)]
		public string TerritoryID { get; set; }

	}
}
