// <auto-generated>
using SQLite;
using NorWnd.Xam.ModelData;

namespace NorWnd.Xam.ModelData.NW
{
	[Table("Employees")]
	public partial class Employee
	{
		public string Address { get; set; }
		public string City { get; set; }
		public string Country { get; set; }

		[PrimaryKey]
		public int EmployeeID { get; set; }

		public string Extension { get; set; }
		public string FirstName { get; set; }
		public string HomePhone { get; set; }
		public string LastName { get; set; }
		public string? Notes { get; set; }
		public string PhotoPath { get; set; }
		public string PostalCode { get; set; }
		public string Region { get; set; }
		public int? ReportsTo { get; set; }
		public string Title { get; set; }
		public string TitleOfCourtesy { get; set; }
	}
}
