// <auto-generated>
using SQLite;
using NorWnd.Xam.ModelData;

namespace NorWnd.Xam.ModelData.NW
{
	[Table("Orders")]
	public partial class Order
	{
		public string CustomerID { get; set; }
		public int? EmployeeID { get; set; }

		[PrimaryKey]
		public int OrderID { get; set; }

		public string ShipAddress { get; set; }
		public string ShipCity { get; set; }
		public string ShipCountry { get; set; }
		public string ShipName { get; set; }
		public string ShipPostalCode { get; set; }
		public string ShipRegion { get; set; }
		public int? ShipVia { get; set; }
	}
}
