// <auto-generated>
using SQLite;
using NorWnd.Xam.ModelData;

namespace NorWnd.Xam.ModelData.NW
{
	[Table("Order Details")]
	public partial class OrderDetail
	{

		[Indexed(Name = "OrderDetail", Order = 1, Unique = true)]
		public int OrderID { get; set; }


		[Indexed(Name = "OrderDetail", Order = 2, Unique = true)]
		public int ProductID { get; set; }

		public short Quantity { get; set; }
	}
}
