// <auto-generated>
using SQLite;
using NorWnd.Xam.ModelData;

namespace NorWnd.Xam.ModelData.NW
{
	[Table("Products")]
	public partial class Product
	{
		public int? CategoryID { get; set; }
		public bool Discontinued { get; set; }

		[PrimaryKey]
		public int ProductID { get; set; }

		public string ProductName { get; set; }
		public string QuantityPerUnit { get; set; }
		public short? ReorderLevel { get; set; }
		public int? SupplierID { get; set; }
		public short? UnitsInStock { get; set; }
		public short? UnitsOnOrder { get; set; }
	}
}
