// <auto-generated>
using SQLite;
using NorWnd.Xam.ModelData;

namespace NorWnd.Xam.ModelData.NW
{
	[Table("Region")]
	public partial class Region
	{
		public string RegionDescription { get; set; }

		[PrimaryKey]
		public int RegionID { get; set; }

	}
}
