// <auto-generated>
using SQLite;
using NorWnd.Xam.ModelData;

namespace NorWnd.Xam.ModelData.NW
{
	[Table("Shippers")]
	public partial class Shipper
	{
		public string CompanyName { get; set; }
		public string Phone { get; set; }

		[PrimaryKey]
		public int ShipperID { get; set; }

	}
}
