// <auto-generated>
using SQLite;
using NorWnd.Xam.ModelData;

namespace NorWnd.Xam.ModelData.NW
{
	[Table("Territories")]
	public partial class Territory
	{
		public int RegionID { get; set; }
		public string TerritoryDescription { get; set; }

		[PrimaryKey]
		public string TerritoryID { get; set; }

	}
}
