// <auto-generated>
using objNW = NorWnd.Xam.ModelObj.NW;
using dataNW = NorWnd.Xam.ModelData.NW;
using dtoNW = NorWnd.DTO.NW;

namespace NorWnd.Xam
{
	public static partial class ModelMapper
	{

		#region ModelObj to ModelDto

		public static dtoNW.Category ToDto(this objNW.Category source)
		{
			return new dtoNW.Category()
			{
				CategoryID = source.CategoryID,
				CategoryName = source.CategoryName,
				Description = source.Description,
			};
		}

		public static dtoNW.CustomerCustomerDemo ToDto(this objNW.CustomerCustomerDemo source)
		{
			return new dtoNW.CustomerCustomerDemo()
			{
				CustomerID = source.CustomerID,
				CustomerTypeID = source.CustomerTypeID,
			};
		}

		public static dtoNW.CustomerDemographic ToDto(this objNW.CustomerDemographic source)
		{
			return new dtoNW.CustomerDemographic()
			{
				CustomerDesc = source.CustomerDesc,
				CustomerTypeID = source.CustomerTypeID,
			};
		}

		public static dtoNW.Customer ToDto(this objNW.Customer source)
		{
			return new dtoNW.Customer()
			{
				Address = source.Address,
				City = source.City,
				CompanyName = source.CompanyName,
				ContactName = source.ContactName,
				ContactTitle = source.ContactTitle,
				Country = source.Country,
				CustomerID = source.CustomerID,
				Fax = source.Fax,
				Phone = source.Phone,
				PostalCode = source.PostalCode,
				Region = source.Region,
			};
		}

		public static dtoNW.Employee ToDto(this objNW.Employee source)
		{
			return new dtoNW.Employee()
			{
				Address = source.Address,
				City = source.City,
				Country = source.Country,
				EmployeeID = source.EmployeeID,
				Extension = source.Extension,
				FirstName = source.FirstName,
				HomePhone = source.HomePhone,
				LastName = source.LastName,
				Notes = source.Notes,
				PhotoPath = source.PhotoPath,
				PostalCode = source.PostalCode,
				Region = source.Region,
				ReportsTo = source.ReportsTo,
				Title = source.Title,
				TitleOfCourtesy = source.TitleOfCourtesy,
			};
		}

		public static dtoNW.EmployeeTerritory ToDto(this objNW.EmployeeTerritory source)
		{
			return new dtoNW.EmployeeTerritory()
			{
				EmployeeID = source.EmployeeID,
				TerritoryID = source.TerritoryID,
			};
		}

		public static dtoNW.OrderDetail ToDto(this objNW.OrderDetail source)
		{
			return new dtoNW.OrderDetail()
			{
				OrderID = source.OrderID,
				ProductID = source.ProductID,
				Quantity = source.Quantity,
			};
		}

		public static dtoNW.Order ToDto(this objNW.Order source)
		{
			return new dtoNW.Order()
			{
				CustomerID = source.CustomerID,
				EmployeeID = source.EmployeeID,
				OrderID = source.OrderID,
				ShipAddress = source.ShipAddress,
				ShipCity = source.ShipCity,
				ShipCountry = source.ShipCountry,
				ShipName = source.ShipName,
				ShipPostalCode = source.ShipPostalCode,
				ShipRegion = source.ShipRegion,
				ShipVia = source.ShipVia,
			};
		}

		public static dtoNW.Product ToDto(this objNW.Product source)
		{
			return new dtoNW.Product()
			{
				CategoryID = source.CategoryID,
				Discontinued = source.Discontinued,
				ProductID = source.ProductID,
				ProductName = source.ProductName,
				QuantityPerUnit = source.QuantityPerUnit,
				ReorderLevel = source.ReorderLevel,
				SupplierID = source.SupplierID,
				UnitsInStock = source.UnitsInStock,
				UnitsOnOrder = source.UnitsOnOrder,
			};
		}

		public static dtoNW.Region ToDto(this objNW.Region source)
		{
			return new dtoNW.Region()
			{
				RegionDescription = source.RegionDescription,
				RegionID = source.RegionID,
			};
		}

		public static dtoNW.Shipper ToDto(this objNW.Shipper source)
		{
			return new dtoNW.Shipper()
			{
				CompanyName = source.CompanyName,
				Phone = source.Phone,
				ShipperID = source.ShipperID,
			};
		}

		public static dtoNW.Supplier ToDto(this objNW.Supplier source)
		{
			return new dtoNW.Supplier()
			{
				Address = source.Address,
				City = source.City,
				CompanyName = source.CompanyName,
				ContactName = source.ContactName,
				ContactTitle = source.ContactTitle,
				Country = source.Country,
				Fax = source.Fax,
				HomePage = source.HomePage,
				Phone = source.Phone,
				PostalCode = source.PostalCode,
				Region = source.Region,
				SupplierID = source.SupplierID,
			};
		}

		public static dtoNW.Sysdiagram ToDto(this objNW.Sysdiagram source)
		{
			return new dtoNW.Sysdiagram()
			{
				definition = source.definition,
				diagram_id = source.diagram_id,
				name = source.name,
				principal_id = source.principal_id,
				version = source.version,
			};
		}

		public static dtoNW.Territory ToDto(this objNW.Territory source)
		{
			return new dtoNW.Territory()
			{
				RegionID = source.RegionID,
				TerritoryDescription = source.TerritoryDescription,
				TerritoryID = source.TerritoryID,
			};
		}


		#endregion ModelObj to ModelDto

		#region ModelData to ModelDto

		public static dtoNW.Category ToDto(this dataNW.Category source)
		{
			return new dtoNW.Category()
			{
				CategoryID = source.CategoryID,
				CategoryName = source.CategoryName,
				Description = source.Description,
			};
		}

		public static dtoNW.CustomerCustomerDemo ToDto(this dataNW.CustomerCustomerDemo source)
		{
			return new dtoNW.CustomerCustomerDemo()
			{
				CustomerID = source.CustomerID,
				CustomerTypeID = source.CustomerTypeID,
			};
		}

		public static dtoNW.CustomerDemographic ToDto(this dataNW.CustomerDemographic source)
		{
			return new dtoNW.CustomerDemographic()
			{
				CustomerDesc = source.CustomerDesc,
				CustomerTypeID = source.CustomerTypeID,
			};
		}

		public static dtoNW.Customer ToDto(this dataNW.Customer source)
		{
			return new dtoNW.Customer()
			{
				Address = source.Address,
				City = source.City,
				CompanyName = source.CompanyName,
				ContactName = source.ContactName,
				ContactTitle = source.ContactTitle,
				Country = source.Country,
				CustomerID = source.CustomerID,
				Fax = source.Fax,
				Phone = source.Phone,
				PostalCode = source.PostalCode,
				Region = source.Region,
			};
		}

		public static dtoNW.Employee ToDto(this dataNW.Employee source)
		{
			return new dtoNW.Employee()
			{
				Address = source.Address,
				City = source.City,
				Country = source.Country,
				EmployeeID = source.EmployeeID,
				Extension = source.Extension,
				FirstName = source.FirstName,
				HomePhone = source.HomePhone,
				LastName = source.LastName,
				Notes = source.Notes,
				PhotoPath = source.PhotoPath,
				PostalCode = source.PostalCode,
				Region = source.Region,
				ReportsTo = source.ReportsTo,
				Title = source.Title,
				TitleOfCourtesy = source.TitleOfCourtesy,
			};
		}

		public static dtoNW.EmployeeTerritory ToDto(this dataNW.EmployeeTerritory source)
		{
			return new dtoNW.EmployeeTerritory()
			{
				EmployeeID = source.EmployeeID,
				TerritoryID = source.TerritoryID,
			};
		}

		public static dtoNW.OrderDetail ToDto(this dataNW.OrderDetail source)
		{
			return new dtoNW.OrderDetail()
			{
				OrderID = source.OrderID,
				ProductID = source.ProductID,
				Quantity = source.Quantity,
			};
		}

		public static dtoNW.Order ToDto(this dataNW.Order source)
		{
			return new dtoNW.Order()
			{
				CustomerID = source.CustomerID,
				EmployeeID = source.EmployeeID,
				OrderID = source.OrderID,
				ShipAddress = source.ShipAddress,
				ShipCity = source.ShipCity,
				ShipCountry = source.ShipCountry,
				ShipName = source.ShipName,
				ShipPostalCode = source.ShipPostalCode,
				ShipRegion = source.ShipRegion,
				ShipVia = source.ShipVia,
			};
		}

		public static dtoNW.Product ToDto(this dataNW.Product source)
		{
			return new dtoNW.Product()
			{
				CategoryID = source.CategoryID,
				Discontinued = source.Discontinued,
				ProductID = source.ProductID,
				ProductName = source.ProductName,
				QuantityPerUnit = source.QuantityPerUnit,
				ReorderLevel = source.ReorderLevel,
				SupplierID = source.SupplierID,
				UnitsInStock = source.UnitsInStock,
				UnitsOnOrder = source.UnitsOnOrder,
			};
		}

		public static dtoNW.Region ToDto(this dataNW.Region source)
		{
			return new dtoNW.Region()
			{
				RegionDescription = source.RegionDescription,
				RegionID = source.RegionID,
			};
		}

		public static dtoNW.Shipper ToDto(this dataNW.Shipper source)
		{
			return new dtoNW.Shipper()
			{
				CompanyName = source.CompanyName,
				Phone = source.Phone,
				ShipperID = source.ShipperID,
			};
		}

		public static dtoNW.Supplier ToDto(this dataNW.Supplier source)
		{
			return new dtoNW.Supplier()
			{
				Address = source.Address,
				City = source.City,
				CompanyName = source.CompanyName,
				ContactName = source.ContactName,
				ContactTitle = source.ContactTitle,
				Country = source.Country,
				Fax = source.Fax,
				HomePage = source.HomePage,
				Phone = source.Phone,
				PostalCode = source.PostalCode,
				Region = source.Region,
				SupplierID = source.SupplierID,
			};
		}

		public static dtoNW.Sysdiagram ToDto(this dataNW.Sysdiagram source)
		{
			return new dtoNW.Sysdiagram()
			{
				definition = source.definition,
				diagram_id = source.diagram_id,
				name = source.name,
				principal_id = source.principal_id,
				version = source.version,
			};
		}

		public static dtoNW.Territory ToDto(this dataNW.Territory source)
		{
			return new dtoNW.Territory()
			{
				RegionID = source.RegionID,
				TerritoryDescription = source.TerritoryDescription,
				TerritoryID = source.TerritoryID,
			};
		}


		#endregion ModelData to ModelDto

		#region ModelDto to ModelObj

		public static objNW.Category ToModelObj(this dtoNW.Category source)
		{
			return new objNW.Category()
			{
				CategoryID = source.CategoryID,
				CategoryName = source.CategoryName,
				Description = source.Description,
			};
		}

		public static objNW.CustomerCustomerDemo ToModelObj(this dtoNW.CustomerCustomerDemo source)
		{
			return new objNW.CustomerCustomerDemo()
			{
				CustomerID = source.CustomerID,
				CustomerTypeID = source.CustomerTypeID,
			};
		}

		public static objNW.CustomerDemographic ToModelObj(this dtoNW.CustomerDemographic source)
		{
			return new objNW.CustomerDemographic()
			{
				CustomerDesc = source.CustomerDesc,
				CustomerTypeID = source.CustomerTypeID,
			};
		}

		public static objNW.Customer ToModelObj(this dtoNW.Customer source)
		{
			return new objNW.Customer()
			{
				Address = source.Address,
				City = source.City,
				CompanyName = source.CompanyName,
				ContactName = source.ContactName,
				ContactTitle = source.ContactTitle,
				Country = source.Country,
				CustomerID = source.CustomerID,
				Fax = source.Fax,
				Phone = source.Phone,
				PostalCode = source.PostalCode,
				Region = source.Region,
			};
		}

		public static objNW.Employee ToModelObj(this dtoNW.Employee source)
		{
			return new objNW.Employee()
			{
				Address = source.Address,
				City = source.City,
				Country = source.Country,
				EmployeeID = source.EmployeeID,
				Extension = source.Extension,
				FirstName = source.FirstName,
				HomePhone = source.HomePhone,
				LastName = source.LastName,
				Notes = source.Notes,
				PhotoPath = source.PhotoPath,
				PostalCode = source.PostalCode,
				Region = source.Region,
				ReportsTo = source.ReportsTo,
				Title = source.Title,
				TitleOfCourtesy = source.TitleOfCourtesy,
			};
		}

		public static objNW.EmployeeTerritory ToModelObj(this dtoNW.EmployeeTerritory source)
		{
			return new objNW.EmployeeTerritory()
			{
				EmployeeID = source.EmployeeID,
				TerritoryID = source.TerritoryID,
			};
		}

		public static objNW.OrderDetail ToModelObj(this dtoNW.OrderDetail source)
		{
			return new objNW.OrderDetail()
			{
				OrderID = source.OrderID,
				ProductID = source.ProductID,
				Quantity = source.Quantity,
			};
		}

		public static objNW.Order ToModelObj(this dtoNW.Order source)
		{
			return new objNW.Order()
			{
				CustomerID = source.CustomerID,
				EmployeeID = source.EmployeeID,
				OrderID = source.OrderID,
				ShipAddress = source.ShipAddress,
				ShipCity = source.ShipCity,
				ShipCountry = source.ShipCountry,
				ShipName = source.ShipName,
				ShipPostalCode = source.ShipPostalCode,
				ShipRegion = source.ShipRegion,
				ShipVia = source.ShipVia,
			};
		}

		public static objNW.Product ToModelObj(this dtoNW.Product source)
		{
			return new objNW.Product()
			{
				CategoryID = source.CategoryID,
				Discontinued = source.Discontinued,
				ProductID = source.ProductID,
				ProductName = source.ProductName,
				QuantityPerUnit = source.QuantityPerUnit,
				ReorderLevel = source.ReorderLevel,
				SupplierID = source.SupplierID,
				UnitsInStock = source.UnitsInStock,
				UnitsOnOrder = source.UnitsOnOrder,
			};
		}

		public static objNW.Region ToModelObj(this dtoNW.Region source)
		{
			return new objNW.Region()
			{
				RegionDescription = source.RegionDescription,
				RegionID = source.RegionID,
			};
		}

		public static objNW.Shipper ToModelObj(this dtoNW.Shipper source)
		{
			return new objNW.Shipper()
			{
				CompanyName = source.CompanyName,
				Phone = source.Phone,
				ShipperID = source.ShipperID,
			};
		}

		public static objNW.Supplier ToModelObj(this dtoNW.Supplier source)
		{
			return new objNW.Supplier()
			{
				Address = source.Address,
				City = source.City,
				CompanyName = source.CompanyName,
				ContactName = source.ContactName,
				ContactTitle = source.ContactTitle,
				Country = source.Country,
				Fax = source.Fax,
				HomePage = source.HomePage,
				Phone = source.Phone,
				PostalCode = source.PostalCode,
				Region = source.Region,
				SupplierID = source.SupplierID,
			};
		}

		public static objNW.Sysdiagram ToModelObj(this dtoNW.Sysdiagram source)
		{
			return new objNW.Sysdiagram()
			{
				definition = source.definition,
				diagram_id = source.diagram_id,
				name = source.name,
				principal_id = source.principal_id,
				version = source.version,
			};
		}

		public static objNW.Territory ToModelObj(this dtoNW.Territory source)
		{
			return new objNW.Territory()
			{
				RegionID = source.RegionID,
				TerritoryDescription = source.TerritoryDescription,
				TerritoryID = source.TerritoryID,
			};
		}


		#endregion ModelDto to ModelObj

		#region ModelDto to ModelData

		public static dataNW.Category ToModelData(this dtoNW.Category source)
		{
			return new dataNW.Category()
			{
				CategoryID = source.CategoryID,
				CategoryName = source.CategoryName,
				Description = source.Description,
			};
		}

		public static dataNW.CustomerCustomerDemo ToModelData(this dtoNW.CustomerCustomerDemo source)
		{
			return new dataNW.CustomerCustomerDemo()
			{
				CustomerID = source.CustomerID,
				CustomerTypeID = source.CustomerTypeID,
			};
		}

		public static dataNW.CustomerDemographic ToModelData(this dtoNW.CustomerDemographic source)
		{
			return new dataNW.CustomerDemographic()
			{
				CustomerDesc = source.CustomerDesc,
				CustomerTypeID = source.CustomerTypeID,
			};
		}

		public static dataNW.Customer ToModelData(this dtoNW.Customer source)
		{
			return new dataNW.Customer()
			{
				Address = source.Address,
				City = source.City,
				CompanyName = source.CompanyName,
				ContactName = source.ContactName,
				ContactTitle = source.ContactTitle,
				Country = source.Country,
				CustomerID = source.CustomerID,
				Fax = source.Fax,
				Phone = source.Phone,
				PostalCode = source.PostalCode,
				Region = source.Region,
			};
		}

		public static dataNW.Employee ToModelData(this dtoNW.Employee source)
		{
			return new dataNW.Employee()
			{
				Address = source.Address,
				City = source.City,
				Country = source.Country,
				EmployeeID = source.EmployeeID,
				Extension = source.Extension,
				FirstName = source.FirstName,
				HomePhone = source.HomePhone,
				LastName = source.LastName,
				Notes = source.Notes,
				PhotoPath = source.PhotoPath,
				PostalCode = source.PostalCode,
				Region = source.Region,
				ReportsTo = source.ReportsTo,
				Title = source.Title,
				TitleOfCourtesy = source.TitleOfCourtesy,
			};
		}

		public static dataNW.EmployeeTerritory ToModelData(this dtoNW.EmployeeTerritory source)
		{
			return new dataNW.EmployeeTerritory()
			{
				EmployeeID = source.EmployeeID,
				TerritoryID = source.TerritoryID,
			};
		}

		public static dataNW.OrderDetail ToModelData(this dtoNW.OrderDetail source)
		{
			return new dataNW.OrderDetail()
			{
				OrderID = source.OrderID,
				ProductID = source.ProductID,
				Quantity = source.Quantity,
			};
		}

		public static dataNW.Order ToModelData(this dtoNW.Order source)
		{
			return new dataNW.Order()
			{
				CustomerID = source.CustomerID,
				EmployeeID = source.EmployeeID,
				OrderID = source.OrderID,
				ShipAddress = source.ShipAddress,
				ShipCity = source.ShipCity,
				ShipCountry = source.ShipCountry,
				ShipName = source.ShipName,
				ShipPostalCode = source.ShipPostalCode,
				ShipRegion = source.ShipRegion,
				ShipVia = source.ShipVia,
			};
		}

		public static dataNW.Product ToModelData(this dtoNW.Product source)
		{
			return new dataNW.Product()
			{
				CategoryID = source.CategoryID,
				Discontinued = source.Discontinued,
				ProductID = source.ProductID,
				ProductName = source.ProductName,
				QuantityPerUnit = source.QuantityPerUnit,
				ReorderLevel = source.ReorderLevel,
				SupplierID = source.SupplierID,
				UnitsInStock = source.UnitsInStock,
				UnitsOnOrder = source.UnitsOnOrder,
			};
		}

		public static dataNW.Region ToModelData(this dtoNW.Region source)
		{
			return new dataNW.Region()
			{
				RegionDescription = source.RegionDescription,
				RegionID = source.RegionID,
			};
		}

		public static dataNW.Shipper ToModelData(this dtoNW.Shipper source)
		{
			return new dataNW.Shipper()
			{
				CompanyName = source.CompanyName,
				Phone = source.Phone,
				ShipperID = source.ShipperID,
			};
		}

		public static dataNW.Supplier ToModelData(this dtoNW.Supplier source)
		{
			return new dataNW.Supplier()
			{
				Address = source.Address,
				City = source.City,
				CompanyName = source.CompanyName,
				ContactName = source.ContactName,
				ContactTitle = source.ContactTitle,
				Country = source.Country,
				Fax = source.Fax,
				HomePage = source.HomePage,
				Phone = source.Phone,
				PostalCode = source.PostalCode,
				Region = source.Region,
				SupplierID = source.SupplierID,
			};
		}

		public static dataNW.Sysdiagram ToModelData(this dtoNW.Sysdiagram source)
		{
			return new dataNW.Sysdiagram()
			{
				definition = source.definition,
				diagram_id = source.diagram_id,
				name = source.name,
				principal_id = source.principal_id,
				version = source.version,
			};
		}

		public static dataNW.Territory ToModelData(this dtoNW.Territory source)
		{
			return new dataNW.Territory()
			{
				RegionID = source.RegionID,
				TerritoryDescription = source.TerritoryDescription,
				TerritoryID = source.TerritoryID,
			};
		}


		#endregion ModelDto to ModelData
	}
}
