// <auto-generated>
using AutoMapper;
using xDTO = NorWnd.DTO.NW;
using xENT = NorWnd.Repository.Entities.NW;

namespace NorWnd.Repository.Infrastructure
{
	public partial class NWAutoMapperProfile : Profile
	{
		public NWAutoMapperProfile()
		{
			InitializeProfile();
			InitializePartial();
		}

		partial void InitializePartial();

		private void InitializeProfile()
		{
			CreateMap<xDTO.Category, xENT.Category>()
Warning - Unable to find Category (from sql) in poco list of generated files. Is there a naming issue?
			CreateMap<xDTO.CustomerCustomerDemo, xENT.CustomerCustomerDemo>()
Warning - Unable to find CustomerCustomerDemo (from sql) in poco list of generated files. Is there a naming issue?
			CreateMap<xDTO.CustomerDemographic, xENT.CustomerDemographic>()
Warning - Unable to find CustomerDemographic (from sql) in poco list of generated files. Is there a naming issue?
			CreateMap<xDTO.Customer, xENT.Customer>()
Warning - Unable to find Customer (from sql) in poco list of generated files. Is there a naming issue?
			CreateMap<xDTO.Employee, xENT.Employee>()
Warning - Unable to find Employee (from sql) in poco list of generated files. Is there a naming issue?
			CreateMap<xDTO.EmployeeTerritory, xENT.EmployeeTerritory>()
Warning - Unable to find EmployeeTerritory (from sql) in poco list of generated files. Is there a naming issue?
			CreateMap<xDTO.OrderDetail, xENT.OrderDetail>()
Warning - Unable to find OrderDetail (from sql) in poco list of generated files. Is there a naming issue?
			CreateMap<xDTO.Order, xENT.Order>()
Warning - Unable to find Order (from sql) in poco list of generated files. Is there a naming issue?
			CreateMap<xDTO.Product, xENT.Product>()
Warning - Unable to find Product (from sql) in poco list of generated files. Is there a naming issue?
			CreateMap<xDTO.Region, xENT.Region>()
Warning - Unable to find Region (from sql) in poco list of generated files. Is there a naming issue?
			CreateMap<xDTO.Shipper, xENT.Shipper>()
Warning - Unable to find Shipper (from sql) in poco list of generated files. Is there a naming issue?
			CreateMap<xDTO.Supplier, xENT.Supplier>()
Warning - Unable to find Supplier (from sql) in poco list of generated files. Is there a naming issue?
			CreateMap<xDTO.Sysdiagram, xENT.Sysdiagram>()
			.ReverseMap();

			CreateMap<xDTO.Territory, xENT.Territory>()
Warning - Unable to find Territory (from sql) in poco list of generated files. Is there a naming issue?
		}
	}
}
