// <auto-generated>
using GalaSoft.MvvmLight;
using NorWnd.Xam.ModelObj;

namespace NorWnd.Xam.ModelObj.NW
{
	public partial class Category : ObservableObject
	{
		private int _categoryID;
		private string _categoryName;
		private string? _description;


		public int CategoryID
		{
			get { return _categoryID; }
			set { Set<int>(() => CategoryID, ref _categoryID, value); }
		}

		public string CategoryName
		{
			get { return _categoryName; }
			set { Set<string>(() => CategoryName, ref _categoryName, value); }
		}

		public string? Description
		{
			get { return _description; }
			set { Set<string?>(() => Description, ref _description, value); }
		}

		public virtual System.Collections.Generic.ICollection<Products> Products { get; set; } // Many to many mapping
		public Category()
		{
			Products = new System.Collections.Generic.List<Products>();

			InitializePartial();
		}

		partial void InitializePartial();
	}
}
