// <auto-generated>
using GalaSoft.MvvmLight;
using NorWnd.Xam.ModelObj;

namespace NorWnd.Xam.ModelObj.NW
{
	public partial class CustomerDemographic : ObservableObject
	{
		private string? _customerDesc;
		private string _customerTypeID;


		public string? CustomerDesc
		{
			get { return _customerDesc; }
			set { Set<string?>(() => CustomerDesc, ref _customerDesc, value); }
		}

		public string CustomerTypeID
		{
			get { return _customerTypeID; }
			set { Set<string>(() => CustomerTypeID, ref _customerTypeID, value); }
		}

		public virtual System.Collections.Generic.ICollection<CustomerCustomerDemo> CustomerCustomerDemos { get; set; } // Many to many mapping
		public CustomerDemographic()
		{
			CustomerCustomerDemos = new System.Collections.Generic.List<CustomerCustomerDemo>();

			InitializePartial();
		}

		partial void InitializePartial();
	}
}
