// <auto-generated>
using GalaSoft.MvvmLight;
using NorWnd.Xam.ModelObj;

namespace NorWnd.Xam.ModelObj.NW
{
	public partial class Customer : ObservableObject
	{
		private string _address;
		private string _city;
		private string _companyName;
		private string _contactName;
		private string _contactTitle;
		private string _country;
		private string _customerID;
		private string _fax;
		private string _phone;
		private string _postalCode;
		private string _region;


		public string Address
		{
			get { return _address; }
			set { Set<string>(() => Address, ref _address, value); }
		}

		public string City
		{
			get { return _city; }
			set { Set<string>(() => City, ref _city, value); }
		}

		public string CompanyName
		{
			get { return _companyName; }
			set { Set<string>(() => CompanyName, ref _companyName, value); }
		}

		public string ContactName
		{
			get { return _contactName; }
			set { Set<string>(() => ContactName, ref _contactName, value); }
		}

		public string ContactTitle
		{
			get { return _contactTitle; }
			set { Set<string>(() => ContactTitle, ref _contactTitle, value); }
		}

		public string Country
		{
			get { return _country; }
			set { Set<string>(() => Country, ref _country, value); }
		}

		public string CustomerID
		{
			get { return _customerID; }
			set { Set<string>(() => CustomerID, ref _customerID, value); }
		}

		public string Fax
		{
			get { return _fax; }
			set { Set<string>(() => Fax, ref _fax, value); }
		}

		public string Phone
		{
			get { return _phone; }
			set { Set<string>(() => Phone, ref _phone, value); }
		}

		public string PostalCode
		{
			get { return _postalCode; }
			set { Set<string>(() => PostalCode, ref _postalCode, value); }
		}

		public string Region
		{
			get { return _region; }
			set { Set<string>(() => Region, ref _region, value); }
		}

		public virtual System.Collections.Generic.ICollection<CustomerCustomerDemo> CustomerCustomerDemos { get; set; } // Many to many mapping
		public virtual System.Collections.Generic.ICollection<Orders> Orders { get; set; } // Many to many mapping
		public Customer()
		{
			CustomerCustomerDemos = new System.Collections.Generic.List<CustomerCustomerDemo>();
			Orders = new System.Collections.Generic.List<Orders>();

			InitializePartial();
		}

		partial void InitializePartial();
	}
}
