// <auto-generated>
using GalaSoft.MvvmLight;
using NorWnd.Xam.ModelObj;

namespace NorWnd.Xam.ModelObj.NW
{
	public partial class CustomerCustomerDemo : ObservableObject
	{
		private string _customerID;
		private string _customerTypeID;


		public string CustomerID
		{
			get { return _customerID; }
			set { Set<string>(() => CustomerID, ref _customerID, value); }
		}

		public string CustomerTypeID
		{
			get { return _customerTypeID; }
			set { Set<string>(() => CustomerTypeID, ref _customerTypeID, value); }
		}

		public virtual CustomerDemographics CustomerDemographics { get; set; } 
		public virtual Customers Customers { get; set; } 
		public CustomerCustomerDemo()
		{

			InitializePartial();
		}

		partial void InitializePartial();
	}
}
