// <auto-generated>
using GalaSoft.MvvmLight;
using NorWnd.Xam.ModelObj;

namespace NorWnd.Xam.ModelObj.NW
{
	public partial class EmployeeTerritory : ObservableObject
	{
		private int _employeeID;
		private string _territoryID;


		public int EmployeeID
		{
			get { return _employeeID; }
			set { Set<int>(() => EmployeeID, ref _employeeID, value); }
		}

		public string TerritoryID
		{
			get { return _territoryID; }
			set { Set<string>(() => TerritoryID, ref _territoryID, value); }
		}

		public virtual Employees Employees { get; set; } 
		public virtual Territories Territories { get; set; } 
		public EmployeeTerritory()
		{

			InitializePartial();
		}

		partial void InitializePartial();
	}
}
