// <auto-generated>
using GalaSoft.MvvmLight;
using NorWnd.Xam.ModelObj;

namespace NorWnd.Xam.ModelObj.NW
{
	public partial class Employee : ObservableObject
	{
		private string _address;
		private string _city;
		private string _country;
		private int _employeeID;
		private string _extension;
		private string _firstName;
		private string _homePhone;
		private string _lastName;
		private string? _notes;
		private string _photoPath;
		private string _postalCode;
		private string _region;
		private int? _reportsTo;
		private string _title;
		private string _titleOfCourtesy;


		public string Address
		{
			get { return _address; }
			set { Set<string>(() => Address, ref _address, value); }
		}

		public string City
		{
			get { return _city; }
			set { Set<string>(() => City, ref _city, value); }
		}

		public string Country
		{
			get { return _country; }
			set { Set<string>(() => Country, ref _country, value); }
		}

		public int EmployeeID
		{
			get { return _employeeID; }
			set { Set<int>(() => EmployeeID, ref _employeeID, value); }
		}

		public string Extension
		{
			get { return _extension; }
			set { Set<string>(() => Extension, ref _extension, value); }
		}

		public string FirstName
		{
			get { return _firstName; }
			set { Set<string>(() => FirstName, ref _firstName, value); }
		}

		public string HomePhone
		{
			get { return _homePhone; }
			set { Set<string>(() => HomePhone, ref _homePhone, value); }
		}

		public string LastName
		{
			get { return _lastName; }
			set { Set<string>(() => LastName, ref _lastName, value); }
		}

		public string? Notes
		{
			get { return _notes; }
			set { Set<string?>(() => Notes, ref _notes, value); }
		}

		public string PhotoPath
		{
			get { return _photoPath; }
			set { Set<string>(() => PhotoPath, ref _photoPath, value); }
		}

		public string PostalCode
		{
			get { return _postalCode; }
			set { Set<string>(() => PostalCode, ref _postalCode, value); }
		}

		public string Region
		{
			get { return _region; }
			set { Set<string>(() => Region, ref _region, value); }
		}

		public int? ReportsTo
		{
			get { return _reportsTo; }
			set { Set<int?>(() => ReportsTo, ref _reportsTo, value); }
		}

		public string Title
		{
			get { return _title; }
			set { Set<string>(() => Title, ref _title, value); }
		}

		public string TitleOfCourtesy
		{
			get { return _titleOfCourtesy; }
			set { Set<string>(() => TitleOfCourtesy, ref _titleOfCourtesy, value); }
		}

		public virtual System.Collections.Generic.ICollection<Employees> Employees1s { get; set; } // Many to many mapping
		public virtual System.Collections.Generic.ICollection<EmployeeTerritories> EmployeeTerritories { get; set; } // Many to many mapping
		public virtual System.Collections.Generic.ICollection<Orders> Orders { get; set; } // Many to many mapping
		public virtual Employees Employees_ReportsTo { get; set; } 
		public Employee()
		{
			Employees1s = new System.Collections.Generic.List<Employees>();
			EmployeeTerritories = new System.Collections.Generic.List<EmployeeTerritories>();
			Orders = new System.Collections.Generic.List<Orders>();

			InitializePartial();
		}

		partial void InitializePartial();
	}
}
