// <auto-generated>
using GalaSoft.MvvmLight;
using NorWnd.Xam.ModelObj;

namespace NorWnd.Xam.ModelObj.NW
{
	public partial class OrderDetail : ObservableObject
	{
		private int _orderID;
		private int _productID;
		private short _quantity;


		public int OrderID
		{
			get { return _orderID; }
			set { Set<int>(() => OrderID, ref _orderID, value); }
		}

		public int ProductID
		{
			get { return _productID; }
			set { Set<int>(() => ProductID, ref _productID, value); }
		}

		public short Quantity
		{
			get { return _quantity; }
			set { Set<short>(() => Quantity, ref _quantity, value); }
		}

		public virtual Orders Orders { get; set; } 
		public virtual Products Products { get; set; } 
		public OrderDetail()
		{

			InitializePartial();
		}

		partial void InitializePartial();
	}
}
