// <auto-generated>
using GalaSoft.MvvmLight;
using NorWnd.Xam.ModelObj;

namespace NorWnd.Xam.ModelObj.NW
{
	public partial class Product : ObservableObject
	{
		private int? _categoryID;
		private bool _discontinued;
		private int _productID;
		private string _productName;
		private string _quantityPerUnit;
		private short? _reorderLevel;
		private int? _supplierID;
		private short? _unitsInStock;
		private short? _unitsOnOrder;


		public int? CategoryID
		{
			get { return _categoryID; }
			set { Set<int?>(() => CategoryID, ref _categoryID, value); }
		}

		public bool Discontinued
		{
			get { return _discontinued; }
			set { Set<bool>(() => Discontinued, ref _discontinued, value); }
		}

		public int ProductID
		{
			get { return _productID; }
			set { Set<int>(() => ProductID, ref _productID, value); }
		}

		public string ProductName
		{
			get { return _productName; }
			set { Set<string>(() => ProductName, ref _productName, value); }
		}

		public string QuantityPerUnit
		{
			get { return _quantityPerUnit; }
			set { Set<string>(() => QuantityPerUnit, ref _quantityPerUnit, value); }
		}

		public short? ReorderLevel
		{
			get { return _reorderLevel; }
			set { Set<short?>(() => ReorderLevel, ref _reorderLevel, value); }
		}

		public int? SupplierID
		{
			get { return _supplierID; }
			set { Set<int?>(() => SupplierID, ref _supplierID, value); }
		}

		public short? UnitsInStock
		{
			get { return _unitsInStock; }
			set { Set<short?>(() => UnitsInStock, ref _unitsInStock, value); }
		}

		public short? UnitsOnOrder
		{
			get { return _unitsOnOrder; }
			set { Set<short?>(() => UnitsOnOrder, ref _unitsOnOrder, value); }
		}

		public virtual System.Collections.Generic.ICollection<Order Details> Order Details { get; set; } // Many to many mapping
		public virtual Categories Categories { get; set; } 
		public virtual Suppliers Suppliers { get; set; } 
		public Product()
		{
			Order Details = new System.Collections.Generic.List<Order Details>();

			InitializePartial();
		}

		partial void InitializePartial();
	}
}
