// <auto-generated>
using GalaSoft.MvvmLight;
using NorWnd.Xam.ModelObj;

namespace NorWnd.Xam.ModelObj.NW
{
	public partial class Shipper : ObservableObject
	{
		private string _companyName;
		private string _phone;
		private int _shipperID;


		public string CompanyName
		{
			get { return _companyName; }
			set { Set<string>(() => CompanyName, ref _companyName, value); }
		}

		public string Phone
		{
			get { return _phone; }
			set { Set<string>(() => Phone, ref _phone, value); }
		}

		public int ShipperID
		{
			get { return _shipperID; }
			set { Set<int>(() => ShipperID, ref _shipperID, value); }
		}

		public virtual System.Collections.Generic.ICollection<Orders> Orders { get; set; } // Many to many mapping
		public Shipper()
		{
			Orders = new System.Collections.Generic.List<Orders>();

			InitializePartial();
		}

		partial void InitializePartial();
	}
}
