// <auto-generated>
using GalaSoft.MvvmLight;
using NorWnd.Xam.ModelObj;

namespace NorWnd.Xam.ModelObj.NW
{
	public partial class Sysdiagram : ObservableObject
	{
		private byte[] _definition;
		private int _diagram_id;
		private string _name;
		private int _principal_id;
		private int? _version;


		public byte[] definition
		{
			get { return _definition; }
			set { Set<byte[]>(() => definition, ref _definition, value); }
		}

		public int diagram_id
		{
			get { return _diagram_id; }
			set { Set<int>(() => diagram_id, ref _diagram_id, value); }
		}

		public string name
		{
			get { return _name; }
			set { Set<string>(() => name, ref _name, value); }
		}

		public int principal_id
		{
			get { return _principal_id; }
			set { Set<int>(() => principal_id, ref _principal_id, value); }
		}

		public int? version
		{
			get { return _version; }
			set { Set<int?>(() => version, ref _version, value); }
		}

		public Sysdiagram()
		{

			InitializePartial();
		}

		partial void InitializePartial();
	}
}
