// <auto-generated>
using GalaSoft.MvvmLight;
using NorWnd.Xam.ModelObj;

namespace NorWnd.Xam.ModelObj.NW
{
	public partial class Territory : ObservableObject
	{
		private int _regionID;
		private string _territoryDescription;
		private string _territoryID;


		public int RegionID
		{
			get { return _regionID; }
			set { Set<int>(() => RegionID, ref _regionID, value); }
		}

		public string TerritoryDescription
		{
			get { return _territoryDescription; }
			set { Set<string>(() => TerritoryDescription, ref _territoryDescription, value); }
		}

		public string TerritoryID
		{
			get { return _territoryID; }
			set { Set<string>(() => TerritoryID, ref _territoryID, value); }
		}

		public virtual System.Collections.Generic.ICollection<EmployeeTerritories> EmployeeTerritories { get; set; } // Many to many mapping
		public virtual Region Region { get; set; } 
		public Territory()
		{
			EmployeeTerritories = new System.Collections.Generic.List<EmployeeTerritories>();

			InitializePartial();
		}

		partial void InitializePartial();
	}
}
