// <auto-generated>
using System;
using System.Threading.Tasks;
using System.Web.Http;
using NorWnd.Repository.Interface;
using appEnums = CodeGenHero.EAMVCXamPOCO.Enums;
using CodeGenHero.EAMVCXamPOCO.Interface;
using CodeGenHero.EAMVCXamPOCO.API.Helpers;

namespace NorWnd.API.Controllers.NW
{
	public partial class NWAPIStatusController : NWBaseApiController
	{
		public NWAPIStatusController() : base()
		{
		}

		public NWAPIStatusController(ILoggingService log, INWRepository repository)
			: base(log, repository)
		{
		}

		[HttpGet]
		[VersionedRoute(template: "APIStatus", allowedVersion: 1, Name = "NWAPIStatus")]
		public async Task<IHttpActionResult> Get()
		{
			try
			{
				return Ok();
			}
			catch (Exception ex)
			{
				Error(message: ex.Message, logMessageType: appEnums.LogMessageType.Exception_WebApi, ex: ex);

				if (System.Diagnostics.Debugger.IsAttached)
					System.Diagnostics.Debugger.Break();

				return InternalServerError();
			}
		}
	}
}
