// <auto-generated>
namespace NorWnd.DTO.NW
{
	public partial class Category
	{

		public int CategoryID { get; set; } // Primary key
		public string CategoryName { get; set; }
		public string? Description { get; set; }
		public Unknown image? Picture { get; set; }

	}
}
