// <auto-generated>
namespace NorWnd.DTO.NW
{
	public partial class CustomerDemographic
	{

		public string CustomerTypeID { get; set; } // Primary key
		public string? CustomerDesc { get; set; }

	}
}
