// <auto-generated>
namespace NorWnd.DTO.NW
{
	public partial class CustomerCustomerDemo
	{

		public string CustomerID { get; set; } // Primary key
		public string CustomerTypeID { get; set; } // Primary key

	}
}
