// <auto-generated>
namespace NorWnd.DTO.NW
{
	public partial class EmployeeTerritory
	{

		public int EmployeeID { get; set; } // Primary key
		public string TerritoryID { get; set; } // Primary key

	}
}
