// <auto-generated>
namespace NorWnd.DTO.NW
{
	public partial class Employee
	{

		public int EmployeeID { get; set; } // Primary key
		public string LastName { get; set; }
		public string FirstName { get; set; }
		public string Title { get; set; }
		public string TitleOfCourtesy { get; set; }
		public Unknown datetime? BirthDate { get; set; }
		public Unknown datetime? HireDate { get; set; }
		public string Address { get; set; }
		public string City { get; set; }
		public string Region { get; set; }
		public string PostalCode { get; set; }
		public string Country { get; set; }
		public string HomePhone { get; set; }
		public string Extension { get; set; }
		public Unknown image? Photo { get; set; }
		public string? Notes { get; set; }
		public int? ReportsTo { get; set; }
		public string PhotoPath { get; set; }

	}
}
