// <auto-generated>
namespace NorWnd.DTO.NW
{
	public partial class Order
	{

		public int OrderID { get; set; } // Primary key
		public string CustomerID { get; set; }
		public int? EmployeeID { get; set; }
		public Unknown datetime? OrderDate { get; set; }
		public Unknown datetime? RequiredDate { get; set; }
		public Unknown datetime? ShippedDate { get; set; }
		public int? ShipVia { get; set; }
		public Unknown money? Freight { get; set; }
		public string ShipName { get; set; }
		public string ShipAddress { get; set; }
		public string ShipCity { get; set; }
		public string ShipRegion { get; set; }
		public string ShipPostalCode { get; set; }
		public string ShipCountry { get; set; }

	}
}
