// <auto-generated>
namespace NorWnd.DTO.NW
{
	public partial class OrderDetail
	{

		public int OrderID { get; set; } // Primary key
		public int ProductID { get; set; } // Primary key
		public Unknown money UnitPrice { get; set; }
		public short Quantity { get; set; }
		public Unknown real Discount { get; set; }

	}
}
