// <auto-generated>
namespace NorWnd.DTO.NW
{
	public partial class Shipper
	{

		public int ShipperID { get; set; } // Primary key
		public string CompanyName { get; set; }
		public string Phone { get; set; }

	}
}
