// <auto-generated>
namespace NorWnd.DTO.NW
{
	public partial class Sysdiagram
	{

		public string name { get; set; }
		public int principal_id { get; set; }
		public int diagram_id { get; set; } // Primary key
		public int? version { get; set; }
		public byte[] definition { get; set; }

	}
}
