// <auto-generated>
namespace NorWnd.DTO.NW
{
	public partial class Territory
	{

		public string TerritoryID { get; set; } // Primary key
		public string TerritoryDescription { get; set; }
		public int RegionID { get; set; }

	}
}
