// <auto-generated>
using CodeGenHero.EAMVCXamPOCO.Interface;
using NorWnd.Repository.Entities.NW;
using System.Linq;

namespace NorWnd.Repository.Interface
{
	public interface INWRepositoryCrud : 
		ICRUDOperation<Category>,
		ICRUDOperation<CustomerCustomerDemo>,
		ICRUDOperation<CustomerDemographic>,
		ICRUDOperation<Customer>,
		ICRUDOperation<Employee>,
		ICRUDOperation<EmployeeTerritory>,
		ICRUDOperation<OrderDetail>,
		ICRUDOperation<Order>,
		ICRUDOperation<Product>,
		ICRUDOperation<Region>,
		ICRUDOperation<Shipper>,
		ICRUDOperation<Supplier>,
		ICRUDOperation<Sysdiagram>,
		ICRUDOperation<Territory>
	{

		#region GetQueryable

		IQueryable<Category> GetQueryableCategory();
		IQueryable<CustomerCustomerDemo> GetQueryableCustomerCustomerDemo();
		IQueryable<CustomerDemographic> GetQueryableCustomerDemographic();
		IQueryable<Customer> GetQueryableCustomer();
		IQueryable<Employee> GetQueryableEmployee();
		IQueryable<EmployeeTerritory> GetQueryableEmployeeTerritory();
		IQueryable<OrderDetail> GetQueryableOrderDetail();
		IQueryable<Order> GetQueryableOrder();
		IQueryable<Product> GetQueryableProduct();
		IQueryable<Region> GetQueryableRegion();
		IQueryable<Shipper> GetQueryableShipper();
		IQueryable<Supplier> GetQueryableSupplier();
		IQueryable<Sysdiagram> GetQueryableSysdiagram();
		IQueryable<Territory> GetQueryableTerritory();

		#endregion

	}
}
